/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransferRouteImport } from './routes/_authenticated/transfer'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLocalTransferRouteImport } from './routes/_authenticated/local-transfer'
import { Route as AuthenticatedInternationalTransferRouteImport } from './routes/_authenticated/international-transfer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransferRoute = AuthenticatedTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalTransferRoute =
  AuthenticatedLocalTransferRouteImport.update({
    id: '/local-transfer',
    path: '/local-transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternationalTransferRoute =
  AuthenticatedInternationalTransferRouteImport.update({
    id: '/international-transfer',
    path: '/international-transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/international-transfer': typeof AuthenticatedInternationalTransferRoute
  '/local-transfer': typeof AuthenticatedLocalTransferRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/send': typeof AuthenticatedSendRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/transfer': typeof AuthenticatedTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/international-transfer': typeof AuthenticatedInternationalTransferRoute
  '/local-transfer': typeof AuthenticatedLocalTransferRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/send': typeof AuthenticatedSendRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/transfer': typeof AuthenticatedTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/international-transfer': typeof AuthenticatedInternationalTransferRoute
  '/_authenticated/local-transfer': typeof AuthenticatedLocalTransferRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/transfer': typeof AuthenticatedTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/dashboard'
    | '/international-transfer'
    | '/local-transfer'
    | '/profile'
    | '/send'
    | '/transactions'
    | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounts'
    | '/dashboard'
    | '/international-transfer'
    | '/local-transfer'
    | '/profile'
    | '/send'
    | '/transactions'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/international-transfer'
    | '/_authenticated/local-transfer'
    | '/_authenticated/profile'
    | '/_authenticated/send'
    | '/_authenticated/transactions'
    | '/_authenticated/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transfer': {
      id: '/_authenticated/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AuthenticatedTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/local-transfer': {
      id: '/_authenticated/local-transfer'
      path: '/local-transfer'
      fullPath: '/local-transfer'
      preLoaderRoute: typeof AuthenticatedLocalTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/international-transfer': {
      id: '/_authenticated/international-transfer'
      path: '/international-transfer'
      fullPath: '/international-transfer'
      preLoaderRoute: typeof AuthenticatedInternationalTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInternationalTransferRoute: typeof AuthenticatedInternationalTransferRoute
  AuthenticatedLocalTransferRoute: typeof AuthenticatedLocalTransferRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedTransferRoute: typeof AuthenticatedTransferRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInternationalTransferRoute:
    AuthenticatedInternationalTransferRoute,
  AuthenticatedLocalTransferRoute: AuthenticatedLocalTransferRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedTransferRoute: AuthenticatedTransferRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
